### PR TITLE
Split signing certs for image and provenance

### PR DESCRIPTION
**Pull request by alextserepov**
The pipeline part

### CODE REVIEW

**Review by henrirosten — APPROVED** [review]

**Review by cazfi — APPROVED** [review]

**Comment by henrirosten** [comment]
@alextserepov: actually, should you change this here too: https://github.com/tiiuae/ghaf-jenkins-pipeline/blob/c32531dacb94c5dc750d4affdb31c984cf23adbe/ghaf-main-pipeline.groovy#L113

**Comment by alextserepov** [comment]
> @alextserepov: actually, should you change this here too:
> 
> https://github.com/tiiuae/ghaf-jenkins-pipeline/blob/c32531dacb94c5dc750d4affdb31c984cf23adbe/ghaf-main-pipeline.groovy#L113

Thank you. Done!

**Review by henrirosten — APPROVED** [review]

**Review by joinemm — APPROVED** [review]

**Comment by alextserepov** [comment]
Modified the HW & parallel-HW test pipelines. So, have to re-request review.

**Comment by joinemm** [comment]
please squash and rebase your commits

**Comment by alextserepov** [comment]
> please squash and rebase your commits

Not that I see any difference between this and "squash and merge", but well ... done. ;)

**Review by vjuntunen — APPROVED** [review]

**Pull request merged**
