### PR TITLE
Add tar file of archived outputs

### PR DESCRIPTION
**Pull request by mkaapu**
Adds an option to download build output of target as a tar file.

### CODE REVIEW

**Comment by mkaapu** [comment]
This draft version works only with fmo-os-main-pipeline.groovy pipeline.
The archive_artifacts method is now intended to be used after all tests are done for single target to collect all outputs together.
This solution is also easiest to implement when targets are build in parallel branches, to avoid checking if build output is available or not, etc.

**Comment by mkaapu** [comment]
I tested these changes against already built changes, so I can better see how much this increase build times.
I tried tar with -J option first, but compressing 1 target with xz took just too much time in jenkins-controller (playground setup).
Then I tried with -z option, and FMO-OS with 6 targets took 36 minutes. Still too much in my opinion.
Then I end up to current version without compression.
Building took 12 minutes. I think this is OK. Downside is used disk space in blob storage as output size is doubled.
So only benefit would be to provide a way to download all output files/directories for 1 target as a single tar file.

**Comment by henrirosten** [comment]
@mkaapu: Can we close this?

**Comment by mkaapu** [comment]
> @mkaapu: Can we close this?

This can be closed. Our current handling of artifacts has probably already diverged significantly from this.

**Pull request closed without merging**
